version: '2'

services:
  web:
    image: nginx:1.15.3
    volumes:
    - ./sites/:/etc/nginx/conf.d/
    ports:
    - "8080:80"
    environment:
     RUN_LEVEL: test
    depends_on:
        - "php7"
    links:
        - "php7"
    volumes_from:
      - source    
  php5:
    build: ./images/php/5.6
    depends_on:
        - redis
        - mysql
    links:
        - "redis"
        - "mysql"
    volumes_from:
      - source  
  php7: 
    build: ./images/php/7.2
    depends_on:
        - redis
        - mysql
    links:
        - "redis"
        - "mysql"
    volumes_from:
      - source  
  redis:
    image: redis:4.0.11
    ports:
    - "6379:6379"  
  mysql:
    image: mysql:5.6.41
    ports:
    - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: allgood
    volumes_from:
      - source  
  source:
    image: alpine
    volumes:
      - ~/IdeaProjects/ecommerce:/www/servers/shop.la
      - ~/IdeaProjects/LovelyTao:/www/servers/tao.la   
      - ~/IdeaProjects/demo-php:/www/servers/test.la
      - ~/DockerVolumes/Mysql:/var/lib/mysql