version: '3.3'
volumes: 
  wwwroot:
services:
  web:
    image: nginx:1.15.3
    volumes:
    - ./sites/:/etc/nginx/conf.d/
    - type: volume
      source: wwwroot
      target: /IdeaProjects
      volume:
          nocopy: true
    ports:
    - "80:80"
    depends_on:
        - "php7"
        - "php5"
    links:
        - "php7"
        - "php5"
  php5:
    image: xinghuo/phalcon-1.3.4-php5
    depends_on:
        - redis
        - mysql
        # - memcached
    links:
        - "redis"
        - "mysql"
        # - "memcached"
        - "rabbitmq"
    volumes:
 
    # - wwwroot:/IdeaProjects
    - ./dependency/php/5.6/conf.d:/usr/local/etc/php/conf.d
    - ./dependency/php/5.6/no-debug-non-zts:/usr/local/lib/php/extensions/no-debug-non-zts-20131226
    - ./dependency/php/5.6/built/memcached/libmemcached:/usr/local/libmemcached
    privileged: true
    ports:
      - 9009:9009
    environment:
      - APPLICATION_ENV=development
      - DEVELOPMENT_REDIS_HOST=redis
  php7: 
    build: ./images/php/7.2
    depends_on:
        - redis
        - mysql
        - memcached
    ports:
      - 9100:9000
    links:
        - "redis"
        - "mysql"
        - 'memcached'
    volumes:
      - /Users/chen/IdeaProjects/:/IdeaProjects
      - ./dependency/php/7.2/conf.d:/usr/local/etc/php/conf.d
      - ./dependency/php/7.2/no-debug-non-zts:/usr/local/lib/php/extensions/no-debug-non-zts-20170718
    privileged: true
    environment:
      APPLICATION_ENV: development
      LOGGER_LEVEL: DEBUG
      DEVELOPMENT_REDIS_HOST: redis

  redis:
    image: redis:4.0.11
    ports:
    - "6379:6379"  
    - "16379:16379"  
  mysql:
    image: mysql:5.7
    ports:
    - "3307:3306"  
    environment:
      MYSQL_PASSWORD: dockersql
      MYSQL_ROOT_PASSWORD: dockersql
  rabbitmq:
    build: ./images/rabbitmq
    ports:
        - 5671:5671  
        - 5672:5672
        - 4369:4369 
        - 25672:25672 
        - 15671:15671 
        - 15672:15672
        - 1883:1883
        - 8883:8883
  beanstalk:
    image: schickling/beanstalkd:latest
    ports:
        - 11300:11300
  memcached:
    image: memcached:1.5.12-alpine
    ports:
        - 11211:11211
