version: '2'

services:
  web:
    image: nginx:1.15.3
    volumes:
    - ./sites/:/etc/nginx/conf.d/
    ports:
    - "80:80"
    depends_on:
        - "php7"
    links:
        - "php7"
    volumes_from:
      - source    
  php5:
    build: ./images/php/5.6
    depends_on:
        - redis
        - mysql
        - memcached
    links:
        - "redis"
        - "mysql"
        - "memcached"
    volumes:
    - ./dependency/php/5.6/conf.d:/usr/local/etc/php/conf.d
    - ./dependency/php/5.6/no-debug-non-zts:/usr/local/lib/php/extensions/no-debug-non-zts-20131226
    - ./dependency/php/5.6/built/memcached/libmemcached:/usr/local/libmemcached
    volumes_from:
      - source  
    privileged: true
    environment:
      - APPLICATION_ENV=development
      - DEVELOPMENT_REDIS_HOST=redis
  php7: 
    build: ./images/php/7.2
    depends_on:
        - redis
        - mysql
        - memcached
    links:
        - "redis"
        - "mysql"
        - 'memcached'
    volumes:
    - ./dependency/php/7.2/conf.d:/usr/local/etc/php/conf.d
    - ./dependency/php/7.2/no-debug-non-zts:/usr/local/lib/php/extensions/no-debug-non-zts-20170718
    volumes_from:
      - source  
    privileged: true
    environment:
      APPLICATION_ENV: development

  redis:
    image: redis:4.0.11
    ports:
    - "6379:6379"  
  mysql:
    image: mysql:5.6.41
    ports:
    - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: dockersql
    volumes_from:
      - source  
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
        - 5671:5671  
        - 5672:5672
        - 4369:4369 
        - 25672:25672 
        - 15671:15671 
        - 15672:15672
  beanstalk:
    image: schickling/beanstalkd:latest
    ports:
        - 11300:11300
  php-redis-admin:
    image: faktiva/php-redis-admin
    ports:
        - 18080:80
    volumes:
        - ./tools/php-redis-admin-config.php:/var/www/html/php-redis-admin/app/config/config.php
  memcached:
    image: memcached:1.5.12-alpine
    ports:
        - 11211:11211
  source:
      image: alpine
      volumes:
        - ~/IdeaProjects/ecommerce:/www/servers/shop.la
        - ~/IdeaProjects/LovelyTao:/www/servers/tao.la   
        - ~/IdeaProjects/demo-php:/www/servers/test.la
        - ~/IdeaProjects/spark:/www/servers/spark.la
        - ~/IdeaProjects/taobao-item-spider:/www/servers/spider.la
        - ./projects:/projects
        - ~/DockerVolumes/Mysql:/var/lib/mysql
        - ./dependency:/dependencyx
  # source:
  #   extends:
  #     file: composes/volume-base.yml
  #     service: source