version: '2'

services:
  web:
    image: nginx:1.15.3
    volumes:
    - ./sites/:/etc/nginx/conf.d/
    ports:
    - "80:80"
    depends_on:
        - "php7"
    links:
        - "php7"
    volumes_from:
      - source    
  php5:
    build: ./images/php/5.6
    depends_on:
        - redis
        - mysql
    links:
        - "redis"
        - "mysql"
    # network_mode:my "service:openvpn"
 
    volumes_from:
      - source  
    privileged: true
    environment:
      - APPLICATION_ENV=development
  php7: 
    build: ./images/php/7.2
    depends_on:
        - redis
        - mysql
    links:
        - "redis"
        - "mysql"
    volumes_from:
      - source  
    privileged: true
    environment:
      APPLICATION_ENV: development

  redis:
    image: redis:4.0.11
    ports:
    - "6379:6379"  
  mysql:
    image: mysql:5.6.41
    ports:
    - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: dockersql
    volumes_from:
      - source  
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
        - 5671:5671  
        - 5672:5672
        - 4369:4369 
        - 25672:25672 
        - 15671:15671 
        - 15672:15672
  beanstalk:
    image: schickling/beanstalkd:latest
    ports:
        - 11300:11300
  php-redis-admin:
    image: faktiva/php-redis-admin
    ports:
        - 18080:80
    volumes:
        - ./tools/php-redis-admin-config.php:/var/www/html/php-redis-admin/app/config/config.php
  source:
    image: alpine
    volumes:
      - ~/IdeaProjects/ecommerce:/www/servers/shop.la
      - ~/IdeaProjects/LovelyTao:/www/servers/tao.la   
      - ~/IdeaProjects/demo-php:/www/servers/test.la
      - ./projects/test:/projects/test
      - ~/DockerVolumes/Mysql:/var/lib/mysql

    